[package]
name = "url_shortner"
version = "0.1.0"
edition = "2021"

[dependencies]
askama = "0.12.1"
axum = "0.7.5"
regex = "1.10.6"
serde = "1.0.209"
tokio = { version = "1.40.0", features = ["full"] }
