services:
  shortener:
    build: .
    ports:
      - "8080:8080"
    volumes:
      - type: bind
        source: ./config.toml
        target: /usr/local/config.toml
  db:
    image: "postgres:14"
    environment:
        POSTGRES_PASSWORD: password_here
