url_len = 6
domain_name = "localhost"
http_ip = "127.0.0.1"
port = 8080
db_ip = "127.0.0.1"
db_name = "shortener"
db_user = "postgres"
db_pass = "THISISVERYBAD PLEASE CHANGE ME"
db_port = 5432
db_pool_size = 10
